---
- name: dpkg configure on ubuntu
  command: dpkg --configure -a
  changed_when: false

- name: add git stable apt_repository on Ubuntu
  apt_repository:
    repo: ppa:git-core/ppa
    state: present

- name: install system packages and utils on ubuntu
  apt:
    pkg:
      [
        "ntp",
        "openssl",
        "git",
        "telnet",
        "figlet",
        "git-core",
        "htop",
        "wget",
        "python3-pip",
        "zip",
        "vim",
        "vim-common",
        "curl",
        "git",
        "rsyslog",
        "libjson-xs-perl",
      ]
    state: "{{ state }}"
    update_cache: true
    cache_valid_time: 5400
  changed_when: false

- name: install python packages
  apt:
    name:
      - awscli
      - iotop
    state: "{{ state }}"
  when: aws
